# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nicb
email_name: nicb at Conservatorio Pollini Padova
email_url: n.bernardini@conservatoriopollini.it
description: > # this means to ignore newlines until "baseurl:"
  Nicb's personal website. Nicb is also known as Nicola Bernardini,
  an italian composer from Rome well known to be out of sync with his schedule.
  I guess he hopes to be out of sync with EOL, too.
baseurl: "" # the subpath of your site, e.g. /blog
imageurl: '/img/'
url: 'https://nicb.github.io' # the base hostname & protocol for your site
twitter_username: nbernardini
github_username:  nicb
academia_username: NicolaBernardini
slideshare_username: NicolaBernardini2
soundcloud_username: nicb-4
orcid_username: nicola.bernardini@conservatoriopollini.it
nicb_icon: nicb-low-gray-420x512.jpg

# Build settings
markdown: kramdown
